Update extract_features.py
PolinaBoeva/predictive_models_dota2 pull request #2
Opened 2024-12-23 14:18 UTC by PolinaBoeva

create DataCleaning class for preprocessing

2024-12-25 11:23 UTC, Rai-Fox requested changes

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +class DataPreprocessing:
объект класса не действие, а кто выполняет это действие
так что DataPreprocessor корректнее

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +class DataCleaning:
объект класса не действие, а кто выполняет это действие
так что DataCleaner корректнее

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +    def fit_transform(self, df_train):
Отдельно fit не получится сделать?

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +    def transform(self, df_test):
Нужно добавить везде аннотации типов аргументов и возвращаемых значений

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +    def _calculate_team_stats(self, team_df, team_name, columns_to_aggregate, stats):
неудачно название переменной stats
лучше заменить на что-то типа agg_funcs/aggregate_functions

И желательно добавить в комментарии описание аргументов, чтобы было были как полные докстринги

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +    def _calculate_team_stats(self, team_df, team_name, columns_to_aggregate, stats):
комментарии когда совсем все готово будет и если время на доработку останется

2024-12-25 11:23 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +        for account_id in df_test_agg['account_id'].unique():
это точно можно сделать оптимальнее и красивее

2024-12-25 14:31 UTC, Rai-Fox commented
`Update extract_features.py`
в название коммита осмысленные вещи плиз

2024-12-27 14:19 UTC, Rai-Fox requested changes

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>      def __init__(self):
Если метод пустой, то зачем его добавлять? Планируется его чем-то дополнить?

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          cols_to_drop = ['pings', 'throw', 'loss', 'comeback', 'rank_tier', 'moonshard', 'aghanims_scepter']
А сколько тут столбцов останется? Может лучше явно указывать столбцы, которые оставляем? И зачем мы в принципе храним столбцы, которые сразу дропаем, может их стоит дропнуть заранее и забыть про них?

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)
А почему заполняем только определенные столбцы, а не все?

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          return 0 if pd.isna(row['kills_per_min']) and row['kills'] == 0 else row['kills_per_min']
Не уверен, что это выносят в метод класса
Думаю, что вынести вне класса будет адекватнее, но не уверен

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> -        # Получение match_id, где в Radiant или Dire больше или равно 2 игроков с invalid actions_per_min
Проблема не в комментариях, а в очевидных комментариях
Сами комментарии о каких-то неочевидных строчках полезны

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          for col in group_cols:
Уверен, что это можно сделать в одну строчку с помощью каких-нибудь методов у групбая без цикла

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +        group_cols = [
А что ты делаешь со столбцами не из списка и сколько их

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          stats = ['mean', 'max', 'min']
aggregate_functions

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +        player_columns = [
Почему увидел этот список 4 раза
такого не должно быть

2024-12-27 14:19 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
> +        return df_upload_agg
Я не разбирался, что тут написано, но этих методов не должно быть
Должны быть методы получения обработанных данных для 1 примера и для датафрейма примеров, использующие transform других классов. Все.

2024-12-27 14:46 UTC, PolinaBoeva commented on predictive_models_dota2/data/extract_features.py
>          df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)
На этапе EDA выяснили, что в этих столбцах nan в преобладающем большинстве случаев вызван тем, что этих действий просто не совершалось.

2024-12-27 14:47 UTC, PolinaBoeva commented on predictive_models_dota2/data/extract_features.py
> +class DataPreprocessing:
изменилось в новой версии

2024-12-27 15:08 UTC, Rai-Fox commented on predictive_models_dota2/data/extract_features.py
>          return 0 if pd.isna(row['kills_per_min']) and row['kills'] == 0 else row['kills_per_min']
А почему не fillna(0) просто

2024-12-28 07:56 UTC, PolinaBoeva commented on predictive_models_dota2/data/extract_features.py
> +        group_cols = [
Столбцы не из списка: категориальные + account_id, match_id и start_date_time

2024-12-28 09:23 UTC, PolinaBoeva commented on predictive_models_dota2/data/extract_features.py
> +        player_columns = [
fixed

2024-12-28 09:23 UTC, PolinaBoeva commented on predictive_models_dota2/data/extract_features.py
>          for col in group_cols:
fixed

2024-12-28 12:50 UTC, Rai-Fox approved these changes

2024-12-28 12:52 UTC, merged