Add files via upload
PolinaBoeva/predictive_models_dota2 pull request #6
Opened 2024-12-26 21:28 UTC by chaarse

Добавила файл main.py - EDA streamlit и requirements.txt

2024-12-27 15:35 UTC, Rai-Fox requested changes

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +st.title("Предсказательные модели для Dota 2")
Код должен быть обернут в функцию

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
Название файла чистовое

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.table(df.describe(include='object'))
Судя по тому, что ты оставила комментарий, ты понимаешь, что это отдельная смысловая часть
Выноси отдельные смысловые части в отдельные функции (в домашках по остальным предметам советую тоже)

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +
В отдельную функцию

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig_deaths)
В отдельную функцию

2024-12-27 15:35 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +
В отдельную функцию

2024-12-27 16:05 UTC, Rai-Fox requested changes

2024-12-27 16:05 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.pyplot(fig)
Не вижу смысла смотреть на корреляции с победой у признаков игроков
Мы же все равно предсказываем на основе признаков матчей, где 10 игроков

2024-12-27 16:05 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig6)
Отрисовку графика в отдельную функцию
Предлагаю вынести вспомогательные функции для отрисовки в отдельный файл plots.py
Я например в дз по питону делал вот так https://github.com/Rai-Fox/temperature-data-analysis/blob/main/temperature_data_analysis/plots.py#L9-L34

2024-12-27 16:05 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig3)
Отрисовку графика в отдельную функцию
Предлагаю вынести вспомогательные функции для отрисовки в отдельный файл plots.py
Я например в дз по питону делал вот так https://github.com/Rai-Fox/temperature-data-analysis/blob/main/temperature_data_analysis/plots.py#L9-L34

2024-12-27 16:11 UTC, Rai-Fox commented
+ Хочется названия коммитов, отражающие проделанные изменения: какие графики добавлены, что исправлено, что изменено

2024-12-28 12:01 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
Поменяла на *eda_streamlit.py*

2024-12-28 12:02 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.table(df.describe(include='object'))
Сделано.

2024-12-28 12:02 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +
Сделано.

2024-12-28 12:02 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig_deaths)
Сделано.

2024-12-28 12:04 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +
Сделано.

2024-12-28 12:57 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.dataframe(xp_per_min_table)
Изменила + отсортировала номер матчей по возрастанию.

2024-12-28 12:58 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.dataframe(df)
Весь датасет не грузится в Streamlit, пишет, что файл слишком большой.

2024-12-28 14:47 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.pyplot(fig)
Согласна, убрала.

2024-12-28 15:01 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig_kills)
+

2024-12-28 15:01 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +                            labels={'account_id': 'ID игрока', 'deaths': 'Смерти', 'hero_name': 'Имя героя'})
Готово.

2024-12-28 15:01 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        top_10_heroes = hero_counts.head(10).index.tolist()
Готово.

2024-12-28 15:19 UTC, Rai-Fox commented on inference/streamlit/eda_chaplygina.py
> +        st.dataframe(df)
Мне кажется проблема не в загрузке, а в отображении

2024-12-28 15:19 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        fig1 = px.histogram(filtered_df, x="hero_name", y="kills", color="hero_name",
Готов + для boxplot тоже подправила.

2024-12-28 15:25 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +                       labels={'hero_name': 'Имя героя', 'count': 'Количество'})
Число вхождений в датасет. Исправила.

2024-12-28 15:31 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig6)
Готово.

2024-12-28 15:31 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig10)
Готово.

2024-12-28 15:34 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        fig10 = px.bar(df_top_10, x='hero_name', y='count', color='hero_name',
Переносом графиков в отельный файл, думаю, решается проблема. Там каждый график в отдельной функции с информативным названиям.

2024-12-28 15:34 UTC, chaarse commented on inference/streamlit/eda_chaplygina.py
> +        st.plotly_chart(fig3)
Готово.

2024-12-28 16:17 UTC, Rai-Fox requested changes

2024-12-28 16:17 UTC, Rai-Fox commented on inference/streamlit/plots.py
> +import plotly.express as px
🤨

2024-12-29 14:00 UTC, chaarse commented on inference/streamlit/eda_streamlit.py
> +        def display_dataset_info(df):
+

2024-12-29 14:05 UTC, chaarse commented on inference/streamlit/eda_streamlit.py
> +                fig1 = create_selected_heroes_plot(filtered_df, attribute)
Исправила.

2024-12-29 14:05 UTC, chaarse commented on inference/streamlit/eda_streamlit.py
> +                fig2 = create_box_plot(filtered_df, attribute)
Исправила.

2024-12-29 14:11 UTC, chaarse commented on inference/streamlit/plots.py
> +import plotly.express as px
Убрала.

2024-12-29 14:40 UTC, chaarse commented on inference/streamlit/plots.py
> +    return fig_deaths
Мне не понравилось как эти графики отображаются для всех данных, поэтому добавила выбор игрока из матча и выбор переменой по которой отрисовывать график распределения.

2024-12-29 15:55 UTC, Rai-Fox requested changes

2024-12-29 15:55 UTC, Rai-Fox commented on inference/streamlit/eda_streamlit.py
> +    create_winrate_pie_chart, create_histogram_for_variable, create_kda_scatter_plot
Переносы строк через \ плохо, обычно можно в скобки обернуть
```
from module import (
  func1,
  func2,
  func3,
)
```

Если пишешь в vscode, то там можно нажать alt + shift + F и у тебя отформатируется код нормально

2024-12-29 15:55 UTC, Rai-Fox commented on inference/streamlit/plots.py
> +        raise ValueError(f"Переменная {variable} не найдена в данных.")
А чем отличаются методы кроме title, который тоже можно передавать?

2024-12-29 16:00 UTC, chaarse commented on inference/streamlit/eda_streamlit.py
> +    create_winrate_pie_chart, create_histogram_for_variable, create_kda_scatter_plot
Подправила

2024-12-29 16:10 UTC, chaarse commented on inference/streamlit/plots.py
> +        raise ValueError(f"Переменная {variable} не найдена в данных.")
По сути ничем, убрала лишнюю функцию.

2024-12-29 16:12 UTC, Rai-Fox approved these changes

2024-12-29 16:14 UTC, merged